-   id: check-pyproject
    name: Validate 'pyproject.toml'
    description: Validate 'pyproject.toml'
    entry: pyproject-parser check
    language: python
    files: pyproject.toml
    additional_dependencies: ["consolekit>=1.1.2", "click>=7.1.2"]

-   id: reformat-pyproject
    name: Reformat 'pyproject.toml'
    description: Reformat 'pyproject.toml'
    entry: pyproject-parser reformat
    language: python
    files: pyproject.toml
    additional_dependencies: ["consolekit>=1.1.2", "click>=7.1.2"]
